import Layout from "@/layout"
import theme from "@/theme"
import Provider from "@/trpc/client/provider"
import { ChakraProvider, ColorModeScript } from "@chakra-ui/react"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <ChakraProvider>
          <Provider>
            <Layout>{children}</Layout>
          </Provider>
        </ChakraProvider>
      </body>
    </html>
  )
}
